# Codecov configuration: https://docs.codecov.com/docs/codecov-yaml
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
